spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/HTML?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ekdmsl1216

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
      database-platform: org.hibernate.dialect.MYSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        provider:
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          apple:
            clientId: temp
            clientSecret: temp
            redirectUri: http://localhost:8080//login/oauth2/code/apple
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Apple
            scope:
              - name
              - email
          kakao:
            client-id: "1400a9dcc6cb981dd5604b842b267120"
            client-secret: "wyDslAVtO54Ol8p29r8f80HPqSrn6o6t"
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
  image:
    path: /Users/leeeunda/Downloads
    url: http://localhost:8080/images

springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret-key: e24ee2b4c6991e275c3d0df9ccbb0bffc44fe15d87d20f81261c8cee703723afd68d2ce5f96c7f29fc47bc049181bf7f77de546fa2aa049a6549167a2b042c1c
  access-token:
    expire-period: 604800000
  refresh-token:
    expire-period: 604800000

logging:
  level:
    org.springframework.security: debug
    web: debug

server:
  http-address: http://localhost:8080
  https-address: https://localhost:8080